# Production конфигурация для ДИМБО Пицца
# Используйте: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d

version: "3.8"

services:
  dimbopizza-web:
    # Production оптимизации
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=200  # Еще меньше памяти в production

    # Улучшенный мониторинг в production
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.dimbopizza-web.rule=Host(`dimbopizza.ru`,`www.dimbopizza.ru`)"
      - "traefik.http.routers.dimbopizza-web.tls=true"
      - "traefik.http.routers.dimbopizza-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.dimbopizza-web.loadbalancer.server.port=3478"

  nginx:
    # Активируем nginx в production
    profiles: []
    
    # SSL сертификаты из Let's Encrypt
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/dimbopizza.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/dimbopizza.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - web_static:/var/www/html:ro
      - ./nginx/logs:/var/log/nginx

    # Labels для мониторинга
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Watchtower для автоматических обновлений
  watchtower:
    image: containrrr/watchtower
    container_name: dimbopizza-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *  # Проверка обновлений в 2:00 каждый день
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=system@dimbopizza.ru
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=admin@dimbopizza.ru
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Watchtower не обновляет сам себя

  # Мониторинг с Prometheus (опционально)
  prometheus:
    image: prom/prometheus:latest
    container_name: dimbopizza-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    profiles:
      - monitoring

volumes:
  prometheus_data:
    driver: local