version: "3.8"

# Docker Compose конфигурация для Timeweb Cloud Apps
# Особенности Timeweb:
# ✅ Автоматический Nginx с SSL
# ✅ Автоматический домен + возможность своего  
# ✅ Переменные через панель управления
# ❌ Volumes не сохраняются
# ❌ Порты 80/443 зарезервированы (используем 3478)
# ❌ Только первый сервис проксируется

services:
  # ДИМБО Пицца Web для Timeweb Cloud Apps
  dimbopizza-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dimbopizza-web
    restart: unless-stopped
    
    # Порт для Timeweb (80/443 зарезервированы платформой)
    ports:
      - "3478:3478"
    
    environment:
      # Production Environment
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
      
      # API Configuration
      - VITE_API_URL=https://api.dimbopizza.ru/api/v1/
      - VITE_API_TIMEOUT=15000
      
      # App Configuration
      - VITE_APP_NAME=ДИМБО Пицца
      - VITE_APP_VERSION=1.0.9
      - VITE_APP_DESCRIPTION=Лучшая пицца в Волжске - заказывайте онлайн!
      
      # Domain Configuration (устанавливается через Timeweb панель)
      - VITE_DOMAIN=${DOMAIN:-dimbopizza.ru}
      - VITE_WWW_DOMAIN=${WWW_DOMAIN:-www.dimbopizza.ru}
      
      # Security (HTTPS управляется Timeweb)
      - VITE_ENABLE_HTTPS=true
      - VITE_SECURE_COOKIES=true
      
      # Analytics (задается через переменные Timeweb)
      - VITE_YANDEX_METRIKA_ID=${VITE_YANDEX_METRIKA_ID}
      - VITE_GOOGLE_ANALYTICS_ID=${VITE_GOOGLE_ANALYTICS_ID}
      
      # Telegram Web App
      - VITE_TELEGRAM_BOT_NAME=${VITE_TELEGRAM_BOT_NAME:-DimboPizzaBot}
      - VITE_TELEGRAM_BOT_URL=${VITE_TELEGRAM_BOT_URL:-https://t.me/DimboPizzaBot}
      - VITE_TELEGRAM_WEBAPP_URL=${VITE_TELEGRAM_WEBAPP_URL:-https://dimbopizza.ru}
      - VITE_TELEGRAM_ENABLED=${VITE_TELEGRAM_ENABLED:-true}
      
      # Contact Info
      - VITE_PHONE=${VITE_PHONE:-+7902-105-34-34}
      - VITE_EMAIL=${VITE_EMAIL:-info@dimbopizza.ru}
      - VITE_ADDRESS=${VITE_ADDRESS:-ул.Шестакова, д.1Б, г. Волжск, Республика Марий Эл}
      
      # Payment & Maps
      - VITE_PAYMENT_REDIRECT_URL=${VITE_PAYMENT_REDIRECT_URL:-https://dimbopizza.ru/payment/callback}
      - VITE_YANDEX_MAPS_API_KEY=${VITE_YANDEX_MAPS_API_KEY}
      
      # Features
      - VITE_ENABLE_PWA=true
      - VITE_ENABLE_NOTIFICATIONS=true
      - VITE_ENABLE_GEOLOCATION=true
      
      # Delivery Configuration
      - VITE_DELIVERY_CITY=Волжск
      - VITE_DELIVERY_ZONES_ENABLED=true
      
      # Build Optimization
      - VITE_BUILD_SOURCEMAP=false
      - VITE_BUILD_MINIFY=true
      - VITE_BUILD_CHUNKS=true

    # Health check для Timeweb
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3478/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    # Настройки логирования для Timeweb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Важно: Timeweb Cloud Apps автоматически:
# - Добавляет SSL сертификат
# - Настраивает домен
# - Проксирует запросы на первый сервис
# - Управляет переменными окружения через панель