# Docker Compose override для development
# Этот файл автоматически применяется в дополнение к docker-compose.yml
# Используется для локальной разработки

version: "3.8"

services:
  dimbopizza-web:
    # Использование development target
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    # В development режиме используем bind mount для hot reload
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # Development переменные
      - NODE_ENV=development
      - VITE_API_URL=/api/v1
      - VITE_YANDEX_METRIKA_ID=dev_metrika_id
    ports:
      - "5173:3478"  # Vite dev server
      - "5174:5174"  # HMR port
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3478"]

  # В development отключаем nginx
  nginx:
    profiles:
      - production  # Nginx запускается только с профилем production