version: "3.8"

services:
  # Основное приложение PizzaNat Web для Timeweb Cloud Apps (оптимизировано для 1GB RAM)
  pizzanat-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pizzanat-web
    restart: unless-stopped
    ports:
      - "3478:3478"

    # Ограничения ресурсов для сервера 1GB RAM
    deploy:
      resources:
        limits:
          memory: 512M # Максимум 512MB для контейнера
          cpus: "0.5" # Максимум 50% CPU
        reservations:
          memory: 256M # Минимум 256MB
          cpus: "0.25" # Минимум 25% CPU

    # Минимальный набор переменных окружения
    environment:
      # Node Environment (оптимизация памяти)
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=256

      # API Configuration (только необходимое)
      - VITE_API_URL=https://api.pizzanat.ru/api/v1
      - VITE_API_TIMEOUT=15000

      # App Configuration (базовое)
      - VITE_APP_NAME=PizzaNat
      - VITE_APP_VERSION=1.0.0
      - VITE_APP_DESCRIPTION=Лучшая пицца в городе - заказывайте онлайн!

      # Domain Configuration
      - VITE_DOMAIN=pizzanat.ru

      # Security (минимум)
      - VITE_ENABLE_HTTPS=true
      - VITE_SECURE_COOKIES=true

      # Build Optimization (экономия ресурсов)
      - VITE_BUILD_SOURCEMAP=false
      - VITE_BUILD_MINIFY=true
      - VITE_BUILD_CHUNKS=false # Отключаем chunking для экономии памяти

    # Оптимизированный healthcheck (реже проверки)
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3478/ || exit 1",
        ]
      interval: 60s # Увеличили интервал
      timeout: 5s # Уменьшили таймаут
      retries: 2 # Меньше попыток
      start_period: 30s # Меньше времени ожидания

    # Настройки для экономии ресурсов
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Максимум 10MB логов
        max-file: "2" # Только 2 файла логов

    # Отключаем swap для контейнера
    mem_swappiness: 0
