# Prometheus конфигурация для мониторинга ДИМБО Пицца

global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Мониторинг основного приложения
  - job_name: 'dimbopizza-web'
    static_configs:
      - targets: ['dimbopizza-web:3478']
    metrics_path: '/health'
    scrape_interval: 60s

  # Мониторинг Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093